/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.daycare.views; 

import static edu.neu.csye6200.daycare.views.ChatHere.s;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.ServerSocket;
import java.net.Socket;

/**
 *
 * @author aayush
 */
public class ChatClient extends javax.swing.JPanel {

    /**
     * Creates new form ChatClient
     */
    //static ServerSocket ss;
    static Socket s;
    static DataInputStream din;
    static DataOutputStream dout;
    
    public ChatClient() {
        initComponents();
       fly();
    }

    public void fly(){
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatClient().setVisible(true);
            }
        });
        
        
                try{
//           s= new Socket("127.0.0.1",6942);//running server and client on same system
           s = new Socket("10.0.0.133",6000);
           
           din = new DataInputStream(s.getInputStream());
           dout = new DataOutputStream(s.getOutputStream());
           String msgIn ="";
            System.out.println(din.readUTF());
            
           while(!msgIn.equals("exit")){
               msgIn = din.readUTF();
               ClientView.setText(ClientView.getText().trim()+"\nServer-> "+msgIn);
           }
        }catch(Exception e){
            System.out.println("Error connecting local ip add"+e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClientReply = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ClientView = new javax.swing.JTextArea();
        ClientSend = new javax.swing.JButton();

        ClientView.setColumns(20);
        ClientView.setRows(5);
        jScrollPane1.setViewportView(ClientView);

        ClientSend.setText("Send");
        ClientSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ClientReply, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ClientSend)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClientReply, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClientSend))
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ClientSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientSendActionPerformed
        // TODO add your handling code here:
        try{
        String msgOut ="";
        msgOut=ClientReply.getText().trim();
        dout.writeUTF(msgOut);
        }catch(Exception e){
        
    }
    }//GEN-LAST:event_ClientSendActionPerformed

   
        
//        try{
//           s= new Socket("127.0.0.1",6942);//running server and client on same system
//           din = new DataInputStream(s.getInputStream());
//           dout = new DataOutputStream(s.getOutputStream());
//           String msgIn ="";
//            System.out.println(din.readUTF());
//            
//           while(!msgIn.equals("exit")){
//               msgIn = din.readUTF();
//               ClientView.setText(ClientView.getText().trim()+"\nServer-> "+msgIn);
//           }
//        }catch(Exception e){
//            System.out.println("Error connecting local ip add"+e);
//        }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ClientReply;
    private javax.swing.JButton ClientSend;
    private static javax.swing.JTextArea ClientView;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
