/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.daycare.views;


import edu.neu.csye6200.daycare.controller.DayCareController;
import java.awt.CardLayout;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.Socket;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.SwingWorker;

/**
 *
 * @author jaidevmane
 */
public class ChatHere extends javax.swing.JPanel {

    /**
     * Creates new form ChatHere
     */
    static Socket s;
    static DataInputStream din;
    static DataOutputStream dout;
    
    private JPanel RightPanel;
    private DayCareController controller = null;
    
    public ChatHere(DayCareController controller,JPanel RightPanel) {
        initComponents();
        this.controller=controller;
        this.RightPanel=RightPanel;
        doThis();
    }
    
     public void doThis(){
        SwingWorker<Void,String> worker = new SwingWorker<Void, String>() {

            @Override
            protected Void doInBackground() throws Exception {
                
            try{
//                s= new Socket("172.20.10.9",1201);//
                s = new Socket("10.0.0.133",6000);
//                s= new Socket("10.0.0.153",1201);//
               //s= new Socket("127.0.0.1",1201);//running server and client on same system
               din = new DataInputStream(s.getInputStream());
               dout = new DataOutputStream(s.getOutputStream());
               String msgIn ="";
            
            
                while(!msgIn.equals("exit")){
                    msgIn = din.readUTF();
                    publish(msgIn);
                    //ClientView.setText(ClientView.getText().trim()+"\nServer-> "+msgIn);
                }

            }catch(Exception e){
                System.out.println("Error connecting local ip add"+e);
            }
          return null;
        }

            @Override
            protected void process(List<String> chunks) {
                String msgIn = chunks.get(chunks.size()-1);
               ClientChateTxtArea.setText(ClientChateTxtArea.getText().trim()+"\nServer-> "+msgIn); 
            }
            
            
        };
        
        worker.execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ClientChateTxtArea = new javax.swing.JTextArea();
        ClientSendTxtField = new javax.swing.JTextField();
        ClientSendBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(246, 237, 246));

        ClientChateTxtArea.setColumns(20);
        ClientChateTxtArea.setRows(5);
        jScrollPane1.setViewportView(ClientChateTxtArea);

        ClientSendTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientSendTxtFieldActionPerformed(evt);
            }
        });

        ClientSendBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ClientSendBtn.setIcon(new javax.swing.ImageIcon("/Users/jaidevmane/NetBeansProjects/DayCare Version Control/aayush new/15 Apr 2020/15 Apr 2020/DayCare/src/edu/neu/csye6200/daycare/icons/send.png")); // NOI18N
        ClientSendBtn.setText("Send");
        ClientSendBtn.setBorderPainted(false);
        ClientSendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientSendBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Local Chat Client");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ClientSendTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ClientSendBtn)))
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ClientSendBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ClientSendTxtField))
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ClientSendTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientSendTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientSendTxtFieldActionPerformed

    private void ClientSendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientSendBtnActionPerformed
        // TODO add your handling code here:
        try{
            String msgOut ="";
            msgOut=ClientSendTxtField.getText().trim();
            dout.writeUTF(msgOut);
            ClientChateTxtArea.setText(ClientChateTxtArea.getText().trim()+"\nClient->" +msgOut);
            ClientSendTxtField.setText("");
        }catch(Exception e){

        }
    }//GEN-LAST:event_ClientSendBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ClientChateTxtArea;
    private javax.swing.JButton ClientSendBtn;
    private javax.swing.JTextField ClientSendTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
