/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.daycare.views;

import com.sun.javafx.scene.control.skin.VirtualFlow;
import edu.neu.csye6200.daycare.controller.DayCareController;
import static edu.neu.csye6200.daycare.views.Login.rightPanel;
import static edu.neu.csye6200.daycare.views.Login.setController;
import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author jaidevmane
 */
public class DriverFrame extends javax.swing.JFrame {

    private boolean logged=false;
    
    private static DayCareController controller = new DayCareController();
    
    private final String FILE_PATH_DEADLINE = "deadline.csv";
    
    public static DayCareController getController() {
		return controller;
	}

	public static void setController(DayCareController controller) {
		DriverFrame.controller = controller;
	}
    /**
     * Creates new form DriverFrame
     */
    public DriverFrame() throws Exception {
        initComponents();
        setBtns(logged,"start");
        DayCareController.demo(controller);
        welcomeLabel.setBorder(null);
  
    }
    
    public void setBtns(boolean loggedin,String role){
        if(loggedin && role.equals("admin")){
            AdminBtn.setEnabled(true);
            LoginBtn.setEnabled(false);
            LogoutBtn.setEnabled(true);
            StudBtn.setEnabled(true);
            TeachrBtn.setEnabled(true);
            chatButton.setEnabled(true);
        }else if(loggedin && role.equals("student")){
            AdminBtn.setEnabled(false);
            LoginBtn.setEnabled(false);
            LogoutBtn.setEnabled(true);
            StudBtn.setEnabled(false);
            TeachrBtn.setEnabled(false);
            chatButton.setEnabled(true);
        } else if(loggedin && role.equals("teacher")){
            AdminBtn.setEnabled(false);
            LoginBtn.setEnabled(false);
            LogoutBtn.setEnabled(true);
            StudBtn.setEnabled(true);
            TeachrBtn.setEnabled(false);
            chatButton.setEnabled(false);
        }
        else{
            AdminBtn.setEnabled(false);
            LoginBtn.setEnabled(true);
            LogoutBtn.setEnabled(false);
            StudBtn.setEnabled(false);
            TeachrBtn.setEnabled(false);
            chatButton.setEnabled(false);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WelcomePane = new javax.swing.JPanel();
        MainSplit = new javax.swing.JSplitPane();
        RightPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LeftPanel = new javax.swing.JPanel();
        LoginBtn = new javax.swing.JButton();
        LogoutBtn = new javax.swing.JButton();
        RulesBtn = new javax.swing.JButton();
        AdminBtn = new javax.swing.JButton();
        TeachrBtn = new javax.swing.JButton();
        StudBtn = new javax.swing.JButton();
        chatButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        welcomeLabel = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        immuStatus = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1269, 1000));
        getContentPane().setLayout(new java.awt.CardLayout());

        WelcomePane.setPreferredSize(new java.awt.Dimension(800, 600));

        RightPanel.setBackground(new java.awt.Color(255, 255, 255));
        RightPanel.setLayout(new java.awt.CardLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RightPanel.add(jLabel1, "card2");

        MainSplit.setRightComponent(RightPanel);

        LeftPanel.setBackground(new java.awt.Color(255, 255, 255));

        LoginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/neu/csye6200/daycare/icons/login.png"))); // NOI18N
        LoginBtn.setText("Login");
        LoginBtn.setBorderPainted(false);
        LoginBtn.setOpaque(false);
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });

        LogoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/neu/csye6200/daycare/icons/exit.png"))); // NOI18N
        LogoutBtn.setText("Logout");
        LogoutBtn.setBorderPainted(false);
        LogoutBtn.setContentAreaFilled(false);
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });

        RulesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/neu/csye6200/daycare/icons/rules.png"))); // NOI18N
        RulesBtn.setText("Rules");
        RulesBtn.setBorderPainted(false);
        RulesBtn.setContentAreaFilled(false);
        RulesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RulesBtnActionPerformed(evt);
            }
        });

        AdminBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/neu/csye6200/daycare/icons/admin.png"))); // NOI18N
        AdminBtn.setText("Admin");
        AdminBtn.setBorderPainted(false);
        AdminBtn.setContentAreaFilled(false);
        AdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminBtnActionPerformed(evt);
            }
        });

        TeachrBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/neu/csye6200/daycare/icons/teacher.png"))); // NOI18N
        TeachrBtn.setText("Teacher");
        TeachrBtn.setBorderPainted(false);
        TeachrBtn.setContentAreaFilled(false);
        TeachrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeachrBtnActionPerformed(evt);
            }
        });

        StudBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/neu/csye6200/daycare/icons/student.png"))); // NOI18N
        StudBtn.setText("Student");
        StudBtn.setBorderPainted(false);
        StudBtn.setContentAreaFilled(false);
        StudBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudBtnActionPerformed(evt);
            }
        });

        chatButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/neu/csye6200/daycare/icons/chat.png"))); // NOI18N
        chatButton.setText("Chat");
        chatButton.setBorderPainted(false);
        chatButton.setContentAreaFilled(false);
        chatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatButtonActionPerformed(evt);
            }
        });

        welcomeLabel.setEditable(false);
        welcomeLabel.setColumns(20);
        welcomeLabel.setLineWrap(true);
        welcomeLabel.setRows(5);
        welcomeLabel.setBorder(null);
        welcomeLabel.setOpaque(false);
        jScrollPane1.setViewportView(welcomeLabel);

        immuStatus.setEditable(false);
        immuStatus.setColumns(20);
        immuStatus.setLineWrap(true);
        immuStatus.setRows(5);
        immuStatus.setBorder(null);
        immuStatus.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(immuStatus);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Immunization Tracker");

        javax.swing.GroupLayout LeftPanelLayout = new javax.swing.GroupLayout(LeftPanel);
        LeftPanel.setLayout(LeftPanelLayout);
        LeftPanelLayout.setHorizontalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TeachrBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AdminBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LogoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(LeftPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RulesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LoginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(StudBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(LeftPanelLayout.createSequentialGroup()
                                .addComponent(chatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        LeftPanelLayout.setVerticalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(LoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RulesBtn)
                .addGap(18, 18, 18)
                .addComponent(chatButton)
                .addGap(18, 18, 18)
                .addComponent(StudBtn)
                .addGap(18, 18, 18)
                .addComponent(TeachrBtn)
                .addGap(18, 18, 18)
                .addComponent(AdminBtn)
                .addGap(18, 18, 18)
                .addComponent(LogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        MainSplit.setLeftComponent(LeftPanel);

        javax.swing.GroupLayout WelcomePaneLayout = new javax.swing.GroupLayout(WelcomePane);
        WelcomePane.setLayout(WelcomePaneLayout);
        WelcomePaneLayout.setHorizontalGroup(
            WelcomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainSplit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1182, Short.MAX_VALUE)
        );
        WelcomePaneLayout.setVerticalGroup(
            WelcomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainSplit)
        );

        getContentPane().add(WelcomePane, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        //System.out.println(RightPanel.getLayout());
        try {
            // TODO add your handling code here:
        CardLayout layout = (CardLayout)RightPanel.getLayout();
            System.out.println(RightPanel.getLayout());
        try {
            RightPanel.add(new Login(RightPanel,this,controller));
            layout.next(RightPanel);
        } catch (Exception ex) {
            Logger.getLogger(DriverFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
//        LoginPage lp = new LoginPage(RightPanel);
//        lp.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(DriverFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void RulesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RulesBtnActionPerformed
        // TODO add your handling code here:
        RulesJPanel rjp = new RulesJPanel(controller);
        CardLayout layout = (CardLayout) RightPanel.getLayout();
        RightPanel.add(rjp);
        layout.next(RightPanel);
    }//GEN-LAST:event_RulesBtnActionPerformed

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        // TODO add your handling code here:
        System.out.println(RightPanel.getLayout());
        try {
            // TODO add your handling code here:
        CardLayout layout = (CardLayout)RightPanel.getLayout();
            System.out.println(RightPanel.getLayout());
        try {
            RightPanel.add(new Login(RightPanel,this,controller));
            layout.next(RightPanel);
        } catch (Exception ex) {
            Logger.getLogger(DriverFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
//        LoginPage lp = new LoginPage(RightPanel);
//        lp.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(DriverFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        logged=false;
        immuStatus.setText("");
        welcomeLabel.setText("");
        setBtns(logged,"loggedOut");
    }//GEN-LAST:event_LogoutBtnActionPerformed

    private void StudBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudBtnActionPerformed
        // TODO add your handling code here:
        StudPanel stud = new StudPanel(RightPanel,controller);
        CardLayout layout = (CardLayout) RightPanel.getLayout();
        RightPanel.add(stud);
        layout.next(RightPanel);
    }//GEN-LAST:event_StudBtnActionPerformed

    private void TeachrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeachrBtnActionPerformed
        // TODO add your handling code here:
        TeaPanel stud = new TeaPanel(RightPanel,controller);
        CardLayout layout = (CardLayout) RightPanel.getLayout();
        RightPanel.add(stud);
        layout.next(RightPanel);
    }//GEN-LAST:event_TeachrBtnActionPerformed

    private void AdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminBtnActionPerformed
        try {
            // TODO add your handling code here:
            AdminPan ap = new AdminPan(controller,RightPanel,true,this);
            CardLayout layout = (CardLayout) RightPanel.getLayout();
            RightPanel.add(ap);
            layout.next(RightPanel);
        } catch (IOException ex) {
            Logger.getLogger(DriverFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AdminBtnActionPerformed

    private void chatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatButtonActionPerformed
        // TODO add your handling code here:
//         ChatJPanel cjp = new ChatJPanel();
//        CardLayout layout = (CardLayout) RightPanel.getLayout();
//        RightPanel.add(cjp);
//        layout.next(RightPanel);
        
        ChatOption chatopt = new ChatOption(controller, RightPanel);

       RightPanel.add("ChatClient",chatopt);
       CardLayout layout = (CardLayout) RightPanel.getLayout();
       layout.next(RightPanel);
    }//GEN-LAST:event_chatButtonActionPerformed

   

    public void setLbl(String lbl) {
        welcomeLabel.setText(lbl);
    }

    public void startDeadCheckStu(String fname, String lname, String id) throws InterruptedException{
        SwingWorker<Void,String> worker = new SwingWorker<Void, String>() {
    
           
            @Override
            protected Void doInBackground() throws Exception {
                File file = new File(FILE_PATH_DEADLINE);
                String line="";
                
                
                
                try {
                    BufferedReader br = new BufferedReader(new FileReader(file));
                    while((line=br.readLine())!=null){
              
              
                    String[] stu = line.split(",");
              
                    int updatedDead = Integer.parseInt(stu[5]);
              
              
                    if(stu[0].equals(id)&& stu[1].equals(fname)&&stu[2].equals(lname)){
                        
                    if(updatedDead == 0 || updatedDead < 0){
                        String send = stu[1]+" "+stu[2];
                
                       publish(send);
                    }
                     
                    }
              
                }
          }catch(IOException e){
            System.out.println(e);
        }
                
                
        return null;
        }

            @Override
            protected void process(List<String> chunks) {
                String val = chunks.get(chunks.size()-1); 
                immuStatus.append(val+"\n");
            }
            
        }; 
  
            worker.execute(); 
 
    }
    
     public void startDeadCheckAdmin() throws InterruptedException{
         
         List<String> stuList = new ArrayList<>();
        SwingWorker<Void,List<String>> worker = new SwingWorker<Void, List<String>>() {
           
           
            @Override
            protected Void doInBackground() throws Exception {
                File file = new File(FILE_PATH_DEADLINE);
                String line="";
                
                
                
                try {
                    BufferedReader br = new BufferedReader(new FileReader(file));
                    while((line=br.readLine())!=null){
              
              
                    String[] stu = line.split(",");
              
                    int updatedDead = Integer.parseInt(stu[5]);
              
              
                    if(updatedDead == 0 || updatedDead < 0){
                        String send = stu[1]+" "+stu[2];
                        stuList.add(send);
                       
                    }
                    
                     publish(stuList);
              
                }
                    
                    
          }catch(IOException e){
            System.out.println(e);
        }
        return null;
        }

            @Override
            protected void process(List<List<String>> chunks) {
                List<String> val = chunks.get(chunks.size()-1);
                
                for(String s:val){
                    immuStatus.append(s+"\n");
                }
                
            }
            
       
        }; 
  
            worker.execute(); 
            
      
 
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DriverFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DriverFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DriverFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DriverFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DriverFrame().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(DriverFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminBtn;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JSplitPane MainSplit;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JButton RulesBtn;
    private javax.swing.JButton StudBtn;
    private javax.swing.JButton TeachrBtn;
    private javax.swing.JPanel WelcomePane;
    private javax.swing.JButton chatButton;
    private javax.swing.JTextArea immuStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
