/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.daycare.views;

import edu.neu.csye6200.daycare.controller.DayCareController;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author aayus
 */
public class TeaPanel extends javax.swing.JPanel {

    /**
     * Creates new form TeaPanel
     */
    private static DayCareController controller = null;
    public static JPanel rightPanel;
    public TeaPanel(JPanel rightPanel,DayCareController controller) {
        initComponents();
        this.rightPanel=rightPanel;
        this.controller=controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddTeacherButton = new javax.swing.JButton();
        TeacherInfoButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 1000));

        AddTeacherButton.setFont(new java.awt.Font("Calibri", 3, 20)); // NOI18N
        AddTeacherButton.setIcon(new javax.swing.ImageIcon("/Users/jaidevmane/NetBeansProjects/DayCare Version Control/aayush new/15 Apr 2020/15 Apr 2020/DayCare/src/edu/neu/csye6200/daycare/icons/teacher.png")); // NOI18N
        AddTeacherButton.setText("Add Teacher");
        AddTeacherButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddTeacherButton.setBorderPainted(false);
        AddTeacherButton.setPreferredSize(new java.awt.Dimension(150, 35));
        AddTeacherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTeacherButtonActionPerformed(evt);
            }
        });

        TeacherInfoButton.setFont(new java.awt.Font("Calibri", 3, 20)); // NOI18N
        TeacherInfoButton.setIcon(new javax.swing.ImageIcon("/Users/jaidevmane/NetBeansProjects/DayCare Version Control/aayush new/15 Apr 2020/15 Apr 2020/DayCare/src/edu/neu/csye6200/daycare/icons/info.png")); // NOI18N
        TeacherInfoButton.setText("Teacher Info");
        TeacherInfoButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TeacherInfoButton.setBorderPainted(false);
        TeacherInfoButton.setPreferredSize(new java.awt.Dimension(150, 35));
        TeacherInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherInfoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(AddTeacherButton, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179)
                .addComponent(TeacherInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(460, 460, 460)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddTeacherButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TeacherInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(250, 250, 250))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddTeacherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTeacherButtonActionPerformed
        AddTeaPan ast= new AddTeaPan(controller, rightPanel);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        rightPanel.add(ast);
        layout.next(rightPanel);
    }//GEN-LAST:event_AddTeacherButtonActionPerformed

    private void TeacherInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherInfoButtonActionPerformed
       TeaInfoPan ast= new TeaInfoPan(controller,rightPanel);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        rightPanel.add(ast);
        layout.next(rightPanel);
    }//GEN-LAST:event_TeacherInfoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTeacherButton;
    private javax.swing.JButton TeacherInfoButton;
    // End of variables declaration//GEN-END:variables
}
